services:

  order-db:
    image: mongo:latest
    container_name: order-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - orchestrator-saga
    volumes:
      - order-db-data:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: order-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - orchestrator-saga
    depends_on:
      - order-db


  product-db:
    image: postgres:latest
    container_name: product-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
    networks:
      - orchestrator-saga
    volumes:
      - product-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:latest
    container_name: payment-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment
    networks:
      - orchestrator-saga
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:latest
    container_name: inventory-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    networks:
      - orchestrator-saga
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    platform: linux/amd64
    restart: no
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - kafka-data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: redpandadata/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - order-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@order-db:27017
    ports:
      - "3000:3000"

  orchestrator-service:
    build: ./orchestrator-service
    container_name: orchestrator-service
    depends_on:
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "8080:8080"

  product-validation-service:
    build: ./product-validation-service
    container_name: product-validation-service
    depends_on:
      - product-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_DATABASE=product
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8090:8090"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - payment-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_DATABASE=payment
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8091:8091"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - inventory-db
      - kafka
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=inventory-db
      - DB_PORT=5432
      - DB_DATABASE=inventory
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8092:8092"

networks:
  orchestrator-saga:
    driver: bridge

volumes:
  order-db-data:
  product-db-data:
  payment-db-data:
  inventory-db-data:
  kafka-data: