server:
  port: 8091

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/payment
    username: postgres
    password: postgres

  hikari:
    connection-timeout: 10000 # 10 seconds to wait for a connection from the pool
    maximum-pool-size: 5      # Maximum number of connections in the pool
    minimum-idle: 1           # Minimum idle connections in the pool
    idle-timeout: 60000       # 60 seconds to keep a connection idle in the pool
    max-lifetime: 1800000     # 30 minutes to keep a connection in the pool
    pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      payment-success: payment-success
      payment-fail: payment-fail
    consumer:
      group-id: payment-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF